# Generated by Django 5.2.4 on 2025-09-07 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji ou ícone representativo', max_length=10)),
                ('color', models.CharField(help_text='Cor em hexadecimal (#FF0000)', max_length=7)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.technology')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('technology', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.template')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da etapa')),
                ('step_type', models.CharField(choices=[('boolean', 'Sim/Não'), ('text', 'Texto'), ('choice', 'Múltipla Escolha'), ('code', 'Código'), ('number', 'Número')], default='boolean', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('condition_value', models.CharField(blank=True, help_text='Valor que ativa esta etapa', max_length=200)),
                ('choices', models.JSONField(blank=True, help_text="Opções para step_type='choice'", null=True)),
                ('parent_step', models.ForeignKey(blank=True, help_text='Etapa pai para perguntas condicionais', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.templatestep')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.template')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='python, javascript, etc.', max_length=50)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_example', models.BooleanField(default=True, help_text='Se é um exemplo ou template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='core.templatestep')),
            ],
            options={
                'ordering': ['language', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.template')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.CreateModel(
            name='ProjectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('comment', models.TextField(blank=True, help_text='Comentário adicional do usuário')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.project')),
                ('template_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.templatestep')),
            ],
            options={
                'ordering': ['template_step__order'],
                'unique_together': {('project', 'template_step')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Horas estimadas estudadas')),
                ('level', models.PositiveIntegerField(default=1)),
                ('badges', models.JSONField(default=list, help_text='Lista de badges conquistadas')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'technology')},
            },
        ),
    ]
