# Generated by Django 5.2.4 on 2026-01-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Horas estimadas estudadas')),
                ('level', models.PositiveIntegerField(default=1)),
                ('badges', models.JSONField(default=list, help_text='Lista de badges conquistadas')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'technology')},
            },
        ),
    ]
