# Generated by Django 5.2.4 on 2026-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='technology',
            field=models.CharField(max_length=100),
        ),
    ]
