# Generated by Django 5.2.4 on 2026-01-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprogress_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
