# Generated by Django 5.2.4 on 2026-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_alter_template_technology_delete_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='file_path',
            field=models.CharField(blank=True, help_text='Caminho local do arquivo do template (opcional)', max_length=500, null=True),
        ),
    ]
